### ISSUE TITLE
Implement the brain

### ISSUE THREAD

**Issue by alessandrodalbello** [chesslave/chesslave#17]
Chesslave is composed by four sensorial modules: eyes, hands, mouth and ears. All these "peripheral" senses need to be coordinated by a centralised organ able to read input from one or more modules and send output to one or more others. This organ is the **brain** (awesome idea @maurocchi!).
The brain has to observe, coordinate and notify. All the messages between the senses must pass through it.
A possible approach to its implementation is an event/message-driven module.

**Comment by maurocchi** [comment]
The title is almost comical! :-D

**Comment by alessandrodalbello** [comment]
I didn't notice! :laughing:
