### ISSUE TITLE
Rendering package refactor

### ISSUE THREAD

**Issue by alessandrodalbello** [chesslave/chesslave#28]
I think we have to incentivize a clear project's structure, which can be achieved even with the packaging strategy. In particular, first level packages need to be as few as possible.
In my opinion, `rendering` package is strictly related to `visual` package. We might merge the two packages or, maybe better, move `rendering` into `visual` as a subpackage. What do you think @maurocchi?

**Comment by maurocchi** [comment]
Ok, maybe also `Board/SquareImage`can be placed in `visual.model` package.

**Comment by alessandrodalbello** [comment]
Good idea!
