### ISSUE TITLE
Introduce Mockito in the tests

### ISSUE THREAD

**Issue by alessandrodalbello** [chesslave/chesslave#4]
Currently, we are not using Mockito in the testing code, nor any other sort of mocking tool. There isn't yet an important need to mock interaction with external components of tested classes, but the ability to isolate testing code and verify components' accesses could be worth the introduction of Mockito.

**Comment by maurocchi** [comment]
For me Mockito is very useful in certain cases, however it's important don't abuse of it.
Let's use only if is real necessary. Sometimes, this "necessity" could be index of bad design...

**Comment by alessandrodalbello** [comment]
Yes, I agree, and as you can see from the commits I did in the last days, I used it very few times (only twice to force exception throwings).

**Comment by maurocchi** [comment]
Is this task completed?

**Comment by alessandrodalbello** [comment]
Given what we can do on testing at this point, I think we could close this issue. I was waiting for a more stable `eyes` package's code, but we can refactor tests later on if needed.
